{"version":1,"defects":{"Warning":6,"tests\\Unit\\RouterTest::test_itRegisterARoute":3,"tests\\Unit\\RouterTest::test_noRoutesWhenRouterIsCreated":4,"tests\\Unit\\RouterTest::testThatItThrowsARouterNotFoundException with data set #0":3,"tests\\Unit\\RouterTest::testThatItThrowsARouterNotFoundException with data set #1":3,"tests\\Unit\\RouterTest::testThatItThrowsARouterNotFoundException with data set #2":3,"tests\\Unit\\RouterTest::testThatItThrowsARouterNotFoundException with data set #3":3},"times":{"Warning":0.098,"tests\\Unit\\RouterTest::test_itRegisterARoute":0.108,"tests\\Unit\\RouterTest::test_thatItRegisterARoute":0.133,"tests\\Unit\\RouterTest::test_thatItRegisterAGetRoute":0,"tests\\Unit\\RouterTest::test_thatItRegisterAPostRoute":0,"tests\\Unit\\RouterTest::test_noRoutesWhenRouterIsCreated":0.011,"tests\\Unit\\RouterTest::testThatItRegisterARoute":0.106,"tests\\Unit\\RouterTest::testThatItRegisterAGetRoute":0,"tests\\Unit\\RouterTest::testThatItRegisterAPostRoute":0,"tests\\Unit\\RouterTest::testNoRoutesWhenRouterIsCreated":0.01,"tests\\Unit\\RouterTest::testThatItThrowsARouterNotFoundException with data set #0":0.033,"tests\\Unit\\RouterTest::testThatItThrowsARouterNotFoundException with data set #1":0,"tests\\Unit\\RouterTest::testThatItThrowsARouterNotFoundException with data set #2":0,"tests\\Unit\\RouterTest::testThatItThrowsARouterNotFoundException with data set #3":0,"tests\\Unit\\RouterTest::testItResolvesRoute":0,"tests\\Unit\\RouterTest::testItResolvesRouteFromClosure":0}}